### ISSUE TITLE
Please allow user hide popup with ESC key in Auto mode

### ISSUE THREAD

**Issue by GeekUser2** [CanisLupus/swift-selection-search#8] opened 2016-08-06 11:15 UTC
The only reason why I still use https://addons.mozilla.org/en-US/firefox/addon/selected-search/  is this limitation on Swift Selection Search. For me, SSS is a great addon with many useful settings. However, for  me, it is very annoying the popup persistence. To scroll the page or enable/disable/enable Auto mode using a key combination is not convenient. I need Auto mode enabled all the time.

**Comment by CanisLupus** [comment] 2016-08-08 10:11
Hi there! Do you mean to say that pressing ESC does not hide the popup? Because, supposedly, pressing any key that is not a modifier (like ctrl, shift, etc) should hide the popup (it does on my end). That includes ESC. :) Even in the previous SSS versions, before the many internal changes, ESC should also make it disappear.

Am I understanding this incorrectly? I might be! Otherwise there might exist some weird problem that is maybe not propagating keypress events correctly.

1. Could you tell me which SSS version you have? The most recent is 2.0.2.
2. Does pressing other keys (A, S, 6, Tab, etc) when the popup is open also do nothing?

Thanks!

**Comment by GeekUser2** [comment] 2016-08-09 10:46
Hi,
Thank you for your answer.
Yes, I mean to say that pressing ESC does not hide the popup.:)
I am using SSS version 2.0.2.
Pressing other keys (A, S, 6, Tab, etc) hide the popup. Only ESC and modifier keys (like ctrl, shift, etc) do not hide the popup.
I am still using Firefox 39.0.3 because I want to use all the 126 add-ons that I have installed and enabled.
Maybe the cause of this malfunction is the version of Firefox or a conflict with one add-on.
Perhaps, it will take me several days to find the cause. In the end of my findings I will tell you the results.

**Comment by CanisLupus** [comment] 2016-08-09 10:54
Those are quite a few add-ons! ;) Please do tell me if you find a cause. One possibility is that one of the add-ons binds an event to the pressing of the ESC key and then stops the event from propagating further, meaning that SSS cannot receive the event and hide the popup. This is all speculation, of course. :) There might be something else going on, like you said related to Firefox's version.

**Comment by CanisLupus** [comment] 2016-12-10 19:41
Hi again, @GeekUser2! :) Were you able to find what the cause of this issue was? (And if it seems to be related to SSS?) I'm curious about this situation, but will eventually close this issue if nothing new shows up, okay? :)

Cheers!

**Comment by GeekUser2** [comment] 2016-12-12 14:20
Hello,

I'm sorry for my silence. I have no health and no time to investigate the problem.
I think it is better to close the issue. Nevertheless, if in the future I find something I will contact you.
Thank you for your interest.

Best regards,
Vasco M. Esteves

----- Original Message ----- 
From: Daniel Lobo 
To: CanisLupus/swift-selection-search 
Cc: GeekUser2 ; Mention 
Sent: Saturday, December 10, 2016 7:41 PM
Subject: [unclassified: Re: [CanisLupus/swift-selection-search] Please allow user hide popup with ESC key in Auto mode (#8)


Hi again, @GeekUser2! :) Were you able to find what the cause of this issue was? (And if it seems to be related to SSS?) I'm curious about this situation, but will eventually close this issue if nothing new shows up, okay? :)

Cheers!

**Comment by CanisLupus** [comment] 2016-12-12 19:03
Hello! I understand. It's not a problem. :) I'll close this issue, but, if you find something in the future, you should still be able to reply here, even though it's closed.

Cheers,
Daniel

**Closed by CanisLupus** 2016-12-12 19:03 UTC
Labels: needs more info
