### ISSUE TITLE
Strange issue in some websites

### ISSUE THREAD

**Issue by hdd60311** [CanisLupus/swift-selection-search#42] opened 2017-10-30 15:44 UTC
Using 57beta12, addon version 3.1.0
I found that in some websites(example sites : [1](https://shmups.system11.org/index.php) [2](https://bbs.kafan.cn/forum-215-1.html) [3](http://club.tgfcer.com/index.php) ) first time opening these sites and selecting a text the addon works normally. 
But when clicking any link in the page and going to another page with the same tab(not open link in a new tab), selecting a text doesn't make the addon work, it doesn't show the popup window and auto-copy also doesn't work.

**Comment by CanisLupus** [comment] 2017-10-30 21:48
You're right, it seems to fail even after refreshing. I've confirmed it in the Developer Edition of Firefox, which is also 57b12.

It does work normally - as far as I saw - in the current stable version, 56.0. Will investigate. Thank you for the report and examples! :)

**Comment by CanisLupus** [comment] 2017-10-31 22:32
I've submitted SSS v3.3.0 to addons.mozilla.com including a possible fix for this. :) This may be a bug in Firefox, probably introduced in 57. Something is causing the SSS scripts to say they are alive even though they shouldn't be because the page gets changed, so they never get added again.

Thankfully I think I found a way around it. Please confirm if the new SSS version solves the problem for you and I'll close this. :)

Your first example site was very useful because the problem always happened. The others were harder but I also saw it happen in a few situations.

Cheers!
Daniel

**Comment by hdd60311** [comment] 2017-11-01 15:35
Thanks, confirmed that the issue in these sites has been fixed.

**Comment by CanisLupus** [comment] 2017-11-01 21:57
Thank you for confirming. :) Closing!

**Closed by CanisLupus** 2017-11-01 21:57 UTC
Labels: bug
