### ISSUE TITLE
 instagram search

### ISSUE THREAD

**Issue by DuaneW2017** [CanisLupus/swift-selection-search#260] opened 2024-03-02 23:56 UTC
Trying to figure out how to add underscores to a search term.
example: My_search_term
I've searched all over, even asked in reddit.
This worked for hyphnation {searchTerms{ |-}}
But {searchTerms{ |_}} doesnt work for underscore.
I wouldnt be here if the instruction that come with the extension had this info.

## ⚠ Development is on an indefinite break (Sorry!) ⚠

You can read more about this [here](https://github.com/CanisLupus/swift-selection-search/issues/230).

- No feature suggestions! Sorry!
- Please only report very problematic bugs. An issue with a single website is minor and probably due to specific formatting, JavaScript, or security policies in that website.

-------------------

**Describe the problem**
A clear description of what is happening and what should happen.

**How to reproduce the problem**

**Anything else you'd like to include**
What you tried already, screenshots, attachments, examples, etc.

**System info:**
- Browser: [e.g. Firefox, Waterfox, etc]
- Browser version: [e.g. 64]
- System: [e.g. Windows 10, macOS]

**Comment by CanisLupus** [comment] 2024-03-03 18:31
Hi! This should definitely work, unless there's some other addon influencing things (or unless Instagram is very particular about underscores). Could you post your whole search engine text?

Example of a YouTube search replacing spaces with underscores:
`https://www.youtube.com/results?search_query={searchTerms{ |_}}`

**Comment by DuaneW2017** [comment] 2024-03-04 16:10
https://www.instagram.com/{searchTerms{ |_}}
I tried other combination too.
Thank you for replying. 

[SSS settings backup (2024-03-04T16.12.31.250Z).json](https://github.com/CanisLupus/swift-selection-search/files/14484232/SSS.settings.backup.2024-03-04T16.12.31.250Z.json)


the youtube example you gave above does put in underscores, but doesnt in instagram

extensions:
![extensions 2024-03-04 102010](https://github.com/CanisLupus/swift-selection-search/assets/26987542/f287e501-a87b-423d-96d5-91ff882d8532)
![extensions 2024-03-04 102044](https://github.com/CanisLupus/swift-selection-search/assets/26987542/66a306be-4f84-4e32-ae2a-fdd05103a598)

**Comment by CanisLupus** [comment] 2024-03-06 20:42
If you select for example "blah blah words" on some webpage, click the Instagram engine in SSS, and then a new tab opens with the URL as `https://www.instagram.com/blah_blah_words/` then everything is working as intended from SSS's side. :) I tried it on my end and this is what happens.

What do you see when you say it doesn't work? If it simply doesn't replace underscores with spaces then I'd suggest trying to disable all other addons temporarily, restarting the browser and see if the problem persists. I'm not seeing this on my side, at least. Could you give me an example of the URL you are seeing when it fails?

What you wrote works! :) That is, as long as what you are trying to do is open some profile on Instagram that has those words separated by underscores. If it doesn't match any profile it will give you a "Sorry, this page isn't available", which is expected.

If, however, you are trying to use some _actual_ search functionality in Instagram then I sadly am not familiar with it. I don't have an Instagram account 😅 But in that case the URL is likely something different. If so please take a look at `I don't know how to add a particular site...` in the `Instructions` section of SSS options menu. It has some pointers. But maybe you did that already since you have a bunch of search engines in the file you gave me above :)

Let me know if any of this helps!

**Comment by DuaneW2017** [comment] 2024-03-07 04:31
Thank you for your help.
This is working for the first time now.
https://www.instagram.com/{searchTerms{ |_}}

That is what I started with and it wouldn't work. 
I would look up people in my search engine to verify they had Instagram. 
Go check to make sure, then find there name on a webpage and try in SSS. It did, even then, put in the underscores. But it would always give me an error message, Sorry, this page isn't available.

In doing more testing here now, sometimes it works and sometimes I get the Sorry, this page isn't available. Even though I know for sure they have an account.

It has to be instagram.

Thank you so much for taking the time to help me.
In the beginning it wouldnt work at all... but now it does.
To me thats the real mystery.

**Comment by CanisLupus** [comment] 2024-03-11 19:19
Interesting... Mystery indeed! I don't know Instagram so I have no clues here hahah. But I'm glad you figured it out.

I will close this issue! :)

**Closed as completed by CanisLupus** 2024-03-11 19:19 UTC
