### ISSUE TITLE
New lines in a search term

### ISSUE THREAD

**Issue by tehkonst** [CanisLupus/swift-selection-search#261] opened 2024-06-29 03:15 UTC
I have a small question. Is it possible to send a search term with new lines inside for websites like Google Translate?

**Comment by tehkonst** [comment] 2024-06-29 05:35
I found out that new lines remain in a search term when I use the context menu. And they disappear when I use the popup form. So I guess it's a bug.

**Comment by CanisLupus** [comment] 2024-07-03 09:03
Hi! Sadly you are right, this is a limitation of SSS. The issue is known and listed here: https://github.com/CanisLupus/swift-selection-search/issues/228

The context menu gets the selected text through the WebExtensions API (so it works properly), while the page's text selection must be acquired through other means. I think that last time I checked I found it wasn't trivial to get the lines separated, and was afraid of getting some edge cases like text and images selected together. I could be misremembering!

**Comment by CanisLupus** [comment] 2024-07-03 09:04
I'll close this since #228 exists, but yes, it's still an issue. Cheers!

**Closed as completed by CanisLupus** 2024-07-03 09:04 UTC
