### ISSUE TITLE
Not all icons show at Hacker News / ycombinator.com in Waterfox

### ISSUE THREAD

**Issue by vertigo220** [CanisLupus/swift-selection-search#92] opened 2018-05-09 16:21 UTC
In Waterfox 56.1.0x64, only the addon's own icons (copy to clipboard & open as link) and icons from resource://search-plugins/images/ show on the above site. They all show in Firefox 59.0.3x64. I disabled all addons and it didn't change. This may be related to issue #27 but I'm not sure.

**Comment by CanisLupus** [comment] 2018-05-10 23:03
Hey there, could you send me an exact page where this happens? Any page at https://news.ycombinator.com?

Waterfox is not officially supported, but I can try to see what is happening there, because SSS supports Firefox 52+, so it should have been working! :) It could be specific to Waterfox, though.

**Comment by vertigo220** [comment] 2018-05-10 23:59
AFAICT it happens at any page there, including the main page that you linked. The only thing I can figure is maybe it's due to the profile location being different.

**Comment by mazesy** [comment] 2018-05-24 21:46
Similar problem here with SSS's popup on certain sites, i.e. betanews.com, majortgeeks.com where the icons do appear but sort of compressed, as:
![2](https://user-images.githubusercontent.com/31442711/40515276-771aa672-5fac-11e8-9ae8-1c7a3528c9f3.jpg)
Contrarily to their normal display:
![1](https://user-images.githubusercontent.com/31442711/40515317-9e56908e-5fac-11e8-9a4e-a0f94bb4808b.jpg)

**Comment by CanisLupus** [comment] 2018-05-27 16:04
Hey @vertigo220, sorry for taking so long to look at this. It seems you are right, on older Firefox versions, Hacker News seems to block the images from appearing (I tested on Firefox 52, the minimum FF version supported by SSS), just like happens on issue #27.

More recent FF versions might have made it more permissive for add-ons to change pages content without being blocked by content policies, but don't quote me on that. My knowledge of the topic is rather limited. :) Unfortunately, I don't think I can fix this! :|

As for the issue reported by @mazesy, it is unrelated to the topic, but I was looking into it and could easily reproduce the problem, so thanks! I couldn't find what's wrong yet, though. This is strange.

Daniel

**Comment by CanisLupus** [comment] 2018-05-27 16:57
No problem! :) Generally, when this happens it's the websites formatting being unusually nosey and changing things like the format of all images on the page. I've added specific instructions to keep a few formatting attributes free of changes before, but it is impossible to prevent all incompatibilities since the page could use JavaScript to change anything at will.

That said, I couldn't find the problem here yet. Usually it's easy to find. It does look like vertical padding but somehow the calculations still match between a "good" and "bad" page. I'll have to look more. ;)

**Comment by mazesy** [comment] 2018-05-27 17:30
With my issue #96 am I a troublemaker or a whistleblower? lol
I should have been an official beta-tester, a job I particularly dislike! But I do have to report an issues I encounter. Of course the risk is that the issue be related to other settings with the incriminated as innocent as a new-born child... tough.

Thanks. SSS is fantastic.

**Comment by mazesy** [comment] 2018-05-27 19:34
Well, as we've seen it, #96 is a non-issue in fact. Remains this _"squeezed icons"_ oddity for which I've read the reasons in your above comment.

Storms in a glass of water, in fact. No true problem, SSS is OK for certification :+1: =)

**Comment by vertigo220** [comment] 2018-05-27 23:57
No problem @mazesy. It's a minor issue anyways, and I don't suspect I'll be bothered by it much, I just wanted to let you know about it. Interestingly, I just went back and tried it again and now _all_ the icons except the integrated ones (copy text, open link in new tab) are blank, though "hovering" over them still shows their tooltips and I can click on the empty space and they work, so something must have changed with my setup. Maybe if I can figure out what it will give a clue to what's going on with the original issue.

**Comment by vertigo220** [comment] 2018-05-28 00:38
Just found out the same thing happens on taskandpurpose.com

**Comment by mazesy** [comment] 2018-05-28 21:53
OK, @CanisLupus I noticed Issue #97, the one I should have opened initially :=) By the way if you wish maybe my inappropriate comment here on Issue #92 could be passed to #97 ?

I'd like to help resolving @vertigo220 issue here but cannot reproduce it on my Firefox 60.0.1 (x65)
Couldn't reproduce the problem on Bugzilla mentioned in Issue #27 
The ycombinator page mentioned above shows my Issue #97 but all icons are in place.

Introduction comment here above does mention

> In Waterfox 56.1.0x64, only the addon's own icons (copy to clipboard & open as link) and icons from resource://search-plugins/images/ show on the above site. They all show in Firefox 59.0.3x64. I disabled all addons and it didn't change. This may be related to issue #27 but I'm not sure.

So the issue is specific to SSS on Firefox pre-Quantum.as I understand it.

**Comment by vertigo220** [comment] 2018-05-29 19:20
I've [created an issue](https://github.com/MrAlex94/Waterfox/issues/599) on the Waterfox repo, so hopefully that will help in getting this figured out.

**Comment by CanisLupus** [comment] 2018-05-31 19:30
@vertigo220 It seems your issue got answered but the problem happens likely due to the website's content policies, just like in #27.

What puzzles me is that I tested, like I said, on Firefox 52 and was able to reproduce your problem (only the base SSS icons appear), but later versions, such as Firefox 60 (which I'm using now) don't have this problem, even though the content policy should be the same.

**Comment by CanisLupus** [comment] 2018-05-31 19:35
Regarding @mazesy's issue, I think I managed to re-do the way the icons are laid out without causing the squashing issue and without breaking separator widths (which are variable). I'll update issue #97 in due time.

I'll have to test more but next SSS version should have this (not submitting until I do a few more things). :)

**Comment by mazesy** [comment] 2018-05-31 20:11
I have something in mind but it may very well make no sense (I'm not at all a techie):

@vertigo220 , would you happen to be running _uBlock Origin_? If so, in uBO settings there's an option called **_Block CSP reports_**, unchecked by default. Could you try checking it (if you run uBO of course)? 

This may have nothing to do but one can always give it a try ...

**Comment by vertigo220** [comment] 2018-05-31 21:32
I actually have that option checked already. Also, I wasn't using uBO in the fresh Waterfox install I tested. It's definitely related to the latest update of Waterfox, just no idea how.

**Comment by vertigo220** [comment] 2018-05-31 21:46
Also, if it's CSP-related, it seems strange it happens _everywhere_.

**Comment by CanisLupus** [comment] 2018-06-01 12:05
Oh sorry, I meant that the original issue seems related to CSP, although it happens on old Firefox versions but not in recent ones (just like issue #27, I believe). Regarding the changes you experienced with the Waterfox update, those are strange and probably not related to CSP. :)

**Comment by CanisLupus** [comment] 2020-05-19 18:50
Hi everyone!

I'm closing this issue, with the reason being that SSS requires Firefox 63+ since version 3.40.0. (Which should actually also have less problems with website content policies due to internal changes that were only possible after 63+.)

This means that the original issue on Waterfox 56 cannot be solved anymore, already discarding the fact that it was always unclear what the exact problem was.

Sorry if this causes any inconvenience. I hope you understand!

Cheers,
Daniel

**Closed by CanisLupus** 2020-05-19 18:50 UTC
Labels: needs more info
