### ISSUE TITLE
OneNote page on onedrive.live.com crashes and restarts

### ISSUE THREAD

**Issue by qtbr** [CanisLupus/swift-selection-search#180] opened 2020-02-14 20:41 UTC
**Describe the problem**
Microsoft OneNote page crashes from SSS popup, current version 3.41 (A previous version 3.30.0 I have for testing it does not do this). OneNote throws an error "Sorry, we ran into a problem" and reloads the page. 

1. Go to a page on OneNote online (you need a microsoft account)
2. Select some editable text on a page in OneNote
3. If "allow popups on editable field" option is enabled in SSS
4. Then, when your mouse hovers over the SSS popup, the page will crash

My theory, it looks like the SSS popup is colliding with the text formatting contextual popup in OneNote.

**System info:**
- Firefox 72.0.2, Windows 7
- Firefox 72.0.2, Ubuntu 16.04 LTS

**Comment by CanisLupus** [comment] 2020-02-20 22:36
Hi @qtbr, thank you for reporting this and sorry for the delay.

I had a look just now and can confirm the crash in OneNote. More or less like you mentioned, it is caused by hovering one of the icons in the popup or by focusing the popup's optional text box (focus on the text box happens automatically when using the "Shortcut to open popup", so in that case it crashes immediately).

My guess is that OneNote has code that constantly monitors hovered elements to make changes to the page, and it's not ready to deal with the SSS popup. The console gets a few errors similar to this one:
> Error: Permission denied to access property "correspondingUseElement"

This seems like a content policy issue (OneNote can't access elements created from outside of its defined content security policy, so fails when accessing SSS), but it could be something else. The reason a previous version of SSS works while the current one doesn't is unknown. It could be due to SSS now using a browser feature known as Shadow DOM to create the popup as a black box to the page, or maybe due to some changes SSS makes to content policies (although that should improve things, not make them worse).

All just a guess, though. :( Unfortunately I don't think there's much I can do about this right now. It needs a longer analysis to find the exact reasons.

Cheers!
Daniel

**Comment by CanisLupus** [comment] 2020-04-02 18:27
Hi again! Like I mentioned before, I don't think that there's much I can do on my end to fix this issue (since it's an error on OneNote's JavaScript), although it is caused by the popup being in the page.

However, SSS version 3.42.0 adds a "Website blocklist" setting (see #145). With this you can block the popup from appearing on `onedrive.live.com`, which should counter the problem.

I'll close this, but feel free to comment on this decision, especially if you believe that blocking the whole domain onedrive.live.com is a problem (I can try writing a more specific filter using regex, but no promises :p).

Cheers!
Daniel

**Closed by CanisLupus** 2020-04-02 18:27 UTC

**Comment by qtbr** [comment] 2020-04-02 19:24
Seems to work well now! thanks so much.

**Comment by CanisLupus** [comment] 2020-04-02 22:55
Alright, that's great! :)
