### ISSUE TITLE
Popup panel not visible or hidden at window edge on certain sites

### ISSUE THREAD

**Issue by opav** [CanisLupus/swift-selection-search#9] opened 2016-09-12 05:23 UTC
On this site for example:  http://www.horstmuc.de/index.html

Selecting any words doesn't show the popup panel at expected spot.  But if look carefully, the panel is hidden at the top edge of the window, exposing only a few pixel that surprising can still be barely reach by mouse.

Attached screen capture, show a word selected (Purebasic), and mouse able to point at the first search engine, showing tooltip (Amazon US).  SSS version 2.0.5 installed.

![2016-09-12 13_14_58-horst schaeffer s software pages](https://cloud.githubusercontent.com/assets/6770347/18425402/cdcbbbb8-78eb-11e6-82cd-037c4ee686ef.png)

**Comment by opav** [comment] 2016-09-12 05:33
Just tested the older SSS version.  FYI ver 1.x.x works!  The panel appears as expected.  

This issue started with ver 2.x.x. 

Hopefully this helps with the bug fix.

**Comment by CanisLupus** [comment] 2016-09-12 22:52
Hi, opav!

Thank you a lot for the bug report. :) I've managed to test it and it seems to be a bug in the code that tries to keep the panel within the screen. It is always detecting that the popup is below the screen (yes, you read that correctly) and trying to place it within but failing miserably.

I still haven't fixed it and it's already late here, but I'll look into it as soon as I can!

Thanks again!
- Daniel

**Comment by Gitoffthelawn** [comment] 2016-09-13 02:09
Confirmed.  Interestingly, I see the few exposed rows of pixels further towards the right.

**Comment by CanisLupus** [comment] 2016-09-14 22:58
Just to update you both, the issue was related to that page (and many others) having a "non-standard" body with a fixed width and 0 height, among other things. As I was adding the popup to the page as a child of the body and also calculating positions based on it, the zero width and margins made the popup think it was always below the screen (actually, below the body).

I've changed code to append to and use the documentElement instead and changed the calculations a bit. It seems to be working but I'll test it a while more before I submit it, in case I find a crippling bug. I'll keep you updated.

Again, thanks!
Daniel

**Comment by Gitoffthelawn** [comment] 2016-09-15 03:13
Fanstastic!  Thanks!

**Comment by CanisLupus** [comment] 2016-09-16 08:36
SSS version 2.0.6 is now live. :) If no other related problem arises, I'll close this issue after a few days.

- Daniel

**Comment by CanisLupus** [comment] 2016-09-24 10:21
I'll be closing this now. Please create another issue if something is wrong. :)

Cheers,
Daniel

**Closed by CanisLupus** 2016-09-24 10:21 UTC
Labels: bug
