### ISSUE TITLE
black list & auto hide

### ISSUE THREAD

**Issue by e1q3z9c7** [CanisLupus/swift-selection-search#145] opened 2019-07-25 04:53 UTC
**Describe your suggestion**
1. A sites list that disallowed the popup
2. A particular period to auto hide the popup (when cursor is away from the grid)

**Comment by CanisLupus** [comment] 2019-07-25 17:40
Hi and thanks for the suggestions. :) I think someone already mentioned the list of sites (maybe in a review...?) because I already have that noted down in my to-dos, but I'm adding the second one too.

Cheers!
Daniel

**Comment by frm1001xplrr** [comment] 2019-10-05 12:30
Seconded. 

I'm currently working in Google Sheets, and have to disable SSS as it interfers with dropdowns (Font size etc.)

_Per Site Blacklist_ would solve this, but _No Action Timeout_ would be even better, as there are certainly times when SSS is useful on the cell content.

**Comment by CanisLupus** [comment] 2019-10-06 10:53
Hmm can I have more details about the interference with dropdowns? What is happening exactly? I use Google Sheets regularly and don't see issues of note, but there's a lot of settings in SSS and mine can be different and not cause trouble. Would be useful to know! :)

**Comment by frm1001xplrr** [comment] 2019-10-06 11:03
Here, https://i.imgur.com/ZLMSOof.png, I'm setting font size, but being blocked by SSS. 
I suppose I could offset the SSS popup in settings, but that would only accomodate Google Sheets.
I remember editing some PDFs online recently and having the same issue (I don't remember what sites...)

**Comment by CanisLupus** [comment] 2019-10-06 11:11
I see, thanks. It doesn't happen to me because I don't have SSS enabled for editable fields and changed my "Opening behaviour" to "middle mouse button" instead of auto.

**Comment by frm1001xplrr** [comment] 2020-02-10 18:45
Bumping the blacklist feature, because SSS breaks the WPBakery plugin for WordPress, that uses TinyMCE text editor 

Firefox Console report the following on every text selection:
```
Error: Permission denied to access property "ownerDocument"tinymce.min.js:2:19846
    attr https://website.com/wp-includes/js/tinymce/tinymce.min.js?ver=4960-20190918:2
    ATTR https://website.com/wp-includes/js/tinymce/tinymce.min.js?ver=4960-20190918:2
    zt https://website.com/wp-includes/js/tinymce/tinymce.min.js?ver=4960-20190918:2
    r https://website.com/wp-includes/js/tinymce/tinymce.min.js?ver=4960-20190918:2
    select https://website.com/wp-includes/js/tinymce/tinymce.min.js?ver=4960-20190918:2
    _t https://website.com/wp-includes/js/tinymce/tinymce.min.js?ver=4960-20190918:2
    select https://website.com/wp-includes/js/tinymce/tinymce.min.js?ver=4960-20190918:2
    setupSelectedState https://website.com/wp-includes/js/tinymce/tinymce.min.js?ver=4960-20190918:2
    fire https://website.com/wp-includes/js/tinymce/tinymce.min.js?ver=4960-20190918:2
    fire https://website.com/wp-includes/js/tinymce/tinymce.min.js?ver=4960-20190918:2
    nodeChanged https://website.com/wp-includes/js/tinymce/tinymce.min.js?ver=4960-20190918:2
    nodeChanged https://website.com/wp-includes/js/tinymce/tinymce.min.js?ver=4960-20190918:2
    Qh https://website.com/wp-includes/js/tinymce/tinymce.min.js?ver=4960-20190918:2
    fire https://website.com/wp-includes/js/tinymce/tinymce.min.js?ver=4960-20190918:2
    fire https://website.com/wp-includes/js/tinymce/tinymce.min.js?ver=4960-20190918:2
    Dp https://website.com/wp-includes/js/tinymce/tinymce.min.js?ver=4960-20190918:2
    t https://website.com/wp-includes/js/tinymce/tinymce.min.js?ver=4960-20190918:2
    C https://website.com/wp-includes/js/tinymce/tinymce.min.js?ver=4960-20190918:2
    d https://website.com/wp-includes/js/tinymce/tinymce.min.js?ver=4960-20190918:2
```
SSS 3.41.0
Firefox 72.0.2 x64 on Win10Prox64

**Comment by CanisLupus** [comment] 2020-02-10 20:16
Hi @frm1001xplrr, I'll bump the priority on this issue.

I'm curious about that error, though. Does it stop happening with SSS off? If anyone has a way to reproduce this without WordPress or that plugin, please let me know. It is possible that the editor gets confused when SSS adds a new HTML element to the page, since the page IS the HTML editor (if I understand the use-case correctly).

**Comment by CanisLupus** [comment] 2020-04-02 18:17
Hey everyone, version 3.42.0 adds a "Website blocklist" setting, located inside "Popup/icons behaviour", to block the popup from appearing on pages with certain URLs.

Please read the details beside the setting:
![image](https://user-images.githubusercontent.com/532708/78283803-42488280-7516-11ea-8603-40b4248cfb05.png)

Some examples:
`google.com` → Blocks google.com, but not www.google.com nor drive.google.com
`*.google.com` → Blocks www.google.com and drive.google.com, but not google.com
`*google.com` → Blocks google.com, www.google.com, drive.google.com
`drive.google.com` → Blocks drive.google.com
`docs.google.com/spreadsheets` → Blocks docs.google.com/spreadsheets (other pages still work) `/\.com/` → (Regex) Blocks all websites that contain ".com" somewhere in the URL

Please let me know here if you find problems with this setting. I will be closing this issue (the auto-hide feature is noted down in any case) until something comes up.

Cheers!
Daniel

**Closed by CanisLupus** 2020-04-02 18:17 UTC
Labels: enhancement

**Comment by rasmushn** [comment] 2020-04-02 21:07
Awesome!

SSS remains the most useful and my favorite addon! 

Thanks for your continued effort, CL :)

**Comment by frm1001xplrr** [comment] 2020-04-02 21:08
Awesome!

SSS remains the most useful and my favorite addon!

Thanks for your continued effort, CL :)

**Comment by CanisLupus** [comment] 2020-04-02 22:59
Woohoo! :D Happy to read that. ;) Cheers!
