### ISSUE TITLE
popup does not work on opensubtitles.org

### ISSUE THREAD

**Issue by Argolics** [CanisLupus/swift-selection-search#101] opened 2018-06-15 14:35 UTC
SSS v3.22.0's pop up does not work on https://www.opensubtitles.org/ while context menu works just fine.
Tried a few other extension with popups there: Google™ Translator were broken too, while ContextSearch web-ext somehow worked.
EDIT: From a quick glance at browser console this looks like a CSP issue.

**Comment by CanisLupus** [comment] 2018-06-17 15:46
Hey thanks for the report, I can confirm that it happens for me as well. Hmm...

It seems that the popup visibility is getting overridden somehow. The page has a crazy amount of rules to hide very generic things using `display: none !important;`, but that shouldn't affect the popup, since it has itself a rule for `display: inline-block !important;` and it is placed on the element itself using JavaScript (so it is the highest priority rule I think I can apply).

Curiously, disabling the page's display rule in the inspector actually causes the popup to appear, even though it isn't in effect, even according to the browser's inspector.

Can I ask why does this seem like a CSP issue? It may be, since it is strange, but I could find no related errors in the console. Saving the opensubtitles page as html and opening it works, even after manually adding the `display: none !important;` CSS bit.

Daniel

**Comment by Argolics** [comment] 2018-06-17 16:19
> Can I ask why does this seem like a CSP issue?

Hrm, thought i have seen CSP errors related to extensions in webconsole for this particular site, but i guess it was just polluted or i was mistaken, since now i don't see anything relevant. Sorry for the noise then.

**Comment by CanisLupus** [comment] 2018-06-17 16:21
No problem at all. :) I'm not understanding where the problem comes from, actually, so anything is a good guess.

**Comment by ZIEXED** [comment] 2018-06-17 18:37
After disabling CSP (security.csp.enable) the problem still exist so at least we know it's unrelated
The final solution to all this issues (and for better) is using Shadow DOM
( _which unfortunately still disabled by default and won't be enabled until Firefox 63_)
[Using shadow DOM](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM   )

**Comment by CanisLupus** [comment] 2018-06-18 22:27
Very interesting and useful to know. Thanks! It's unfortunate that it will come so late...

**Comment by CanisLupus** [comment] 2019-12-02 18:01
Hey @Argolics, if you still use SSS can you let me know if version 3.40.2 of SSS fixes anything for you? Or if it now appears but some icons are gone?

(Beware of two already-reported bugs that appear in this version - see #156 - which will be fixed in 3.40.3).

I never understood what was happening on OpenSubtitles but a few things changed in SSS. Some updates:

SSS now uses Shadow DOM as suggested by @ZIEXED (thanks!), which made some SSS code simpler internally and avoids sites interfering with the internal element formatting as easily (they still can if they really want to).

However, even when using Shadow DOM, a site's CSP can still block certain images, scripts, styles, etc inside the element. CSP seems independent of where things are in the DOM, and it really should be, to work as intended. :)

To fix the above, SSS now modifies each page's request headers to allow its formatting to work regardless of CSP (extensions work on behalf of users, so they are allowed to do that if they wish).

Since many other extensions also do this, especially ad blockers, it is possible that SSS now conflicts with such extensions on certain sites. For example, I can now see the SSS popup on opensubtitles.org but it is missing all icons that do not belong to SSS itself (only shows copy, open link and the separator). If I disable my ad blocker, the popup shows normally.

I believe this is caused by an issue in Firefox that happens when 2 extensions try to modify the same headers. I'm not sure, however, and I also don't know if I can do anything about it if that's the case, but I'll check that when I can. Another solution is them making extensions exempt from CSP rules entirely, which is also being discussed.

**Comment by CanisLupus** [comment] 2020-02-10 20:12
I'm closing this issue. Feel free to comment here if this still happens to anyone. Thanks!

**Closed by CanisLupus** 2020-02-10 20:12 UTC
Labels: needs more info
