### ISSUE TITLE
Could you pls make a chrome version?

### ISSUE THREAD

**Issue by minshifu** [CanisLupus/swift-selection-search#234] opened 2021-07-03 15:02 UTC
This is a super great addon. It is a pity that chrome browser does not have a comparable extension. Could you pls make a chrome extension? Thank you and best regards!

**Comment by jdreesen** [comment] 2021-07-04 21:58
Please have a look at the readme ;)

Also, this is a duplicate of #184, #148 and #132.

**Comment by CanisLupus** [comment] 2021-07-06 09:35
Thank you so much for the help @jdreesen 😃

Hi @minshifu! Indeed, the links posted above by Jacob should explain why there's no Chrome version. Also, right now SSS is not actively being developed (see #230).

I'll close the issue now, I hope you understand!

**Closed by CanisLupus** 2021-07-06 09:35 UTC
