### ISSUE TITLE
Incompatibility with Tree Style Tabs

### ISSUE THREAD

**Issue by pintassilgo** [CanisLupus/swift-selection-search#21] opened 2017-01-16 08:09 UTC
Option to open tab next to current doesn't work with Tree Style Tabs enabled.

**Comment by CanisLupus** [comment] 2017-01-17 19:23
I installed Tree Style Tabs and was able to confirm the problem. I'm not sure if this is something I can fix, however. It also depends on what Tree Style Tabs does, because it seems to "intercept" tabs being opened in order to place them at the correct indexes for the tree view.

I'll see if there's something I can do. :)

**Comment by CanisLupus** [comment] 2017-02-02 22:00
I never thanked you for the pull request. Thanks! I must say that I intend to look into applying a more general fix to the tab opening instead of explicitly checking for the existence of another plugin. If that is at all possible, of course!

Daniel

**Comment by pintassilgo** [comment] 2017-02-02 22:26
Used by popular extension Reddit Enhancement Suite:
https://github.com/honestbleeps/Reddit-Enhancement-Suite/commit/54d4fd9fb1fd2db0310b09ecd09d4a9921aaf59c#diff-fbf4edb85cda71bac74bf642dcf45e6e

I don't think it will create incompatibility with any other extension, it's just to fix the behavior with TST, another popular extension (100k+ users).

**Comment by CanisLupus** [comment] 2017-10-31 21:32
Hey, @pintassilgo! I was looking into this (and #30) now, since SSS is finally a WebExtension. I installed Tree Style Tab from here: https://addons.mozilla.org/firefox/addon/tree-style-tab/

However, I couldn't find anything wrong with running it alongside SSS. Maybe something was changed on TST, since this was quite a while ago. Opening in new tab (background or not) from the SSS popup seems to place the tab as a child of the currently open tab, which is the expected behavior. Can you please confirm if it works on your end as well, if you still use SSS and TST?

Again, thank you for your pull request and I'm sorry I didn't get to check this until now!

Daniel

**Comment by pintassilgo** [comment] 2017-10-31 22:19
Probably solved, TST was also converted to WebExt.

I have no plans to update TST nor SSS to WebExt with its limitations, so I can't confirm, but it's OK with the fix I proposed.

Thank you anyway.

**Comment by CanisLupus** [comment] 2017-10-31 22:40
I understand. The limitations are very frustrating indeed! Unfortunately Firefox 57 will force most people on the WebExtensions train. (Maybe unless you use Nightly, where it can still run legacy addons...?)

I'll try to confirm this with the user that posted issue 30. If I get confirmation or nothing shows up for a while I'll probably close this and the other issue.

**Comment by pintassilgo** [comment] 2017-10-31 23:25
( Developer Edition (Beta with some tweaks) supports `extensions.legacy.enabled` too. There is also `general.config.filename` (https://www.ghacks.net/2016/08/14/override-firefox-add-on-signing-requirement/) that works even in release version and can execute JS with unlimited privileges (so as powerful as an legacy extension), but the process of converting extensions files to this would be extremely complicated, especially those built with SDK that was already removed from Fx 57. )

**Comment by CanisLupus** [comment] 2017-11-01 22:25
Interesting... At least there's an alternative (albeit rather hidden) to keep legacy extensions. Though I'm guessing that even some of these are likely to be removed from Firefox eventually.

On the topic, user orodeshah showed me in #30 that the incompatibility with TST still exists after all. I somehow managed to test it in the only way that works, which is incredible :facepalm: :)

I'll close this issue since the other one has additional information. I'm still waiting for the miracle that would let me fix this without explicitly checking if TST is running. And now in WebExtensions! But TST probably provides readyToOpenChildTab for other addons to work well alongside it, so I suppose it's the only way.

**Closed by CanisLupus** 2017-11-01 22:25 UTC
Labels: incompatibility
