### ISSUE TITLE
Breaks tree style tab add on

### ISSUE THREAD

**Issue by orodeshah** [CanisLupus/swift-selection-search#30] opened 2017-06-13 03:58 UTC
search opens new tab, new tab should be child of main tab like other new pages and also like other context searches, but it become a new tab under main tab, not its child

**Comment by CanisLupus** [comment] 2017-06-15 13:43
Hi! I believe this is the same as issue #21, but I'll leave it here until fixed. :) The user who first reported the incompatibility between SSS and that plugin has suggested a fix, but I haven't decided if that is the way I want to solve it yet.

Right now SSS is (or better yet "I am") waiting for a Firefox update to the search API for WebExtensions, because it currently does not exist and I can't port the plugin as it currently exists.

**Comment by CanisLupus** [comment] 2017-10-31 22:42
It's been a long time, but SSS is finally a WebExtension, so I was looking into this, as I mentioned in issue #21 just now. I installed Tree Style Tab from here: https://addons.mozilla.org/firefox/addon/tree-style-tab/

However, I couldn't find anything wrong with running it alongside SSS. Maybe something was changed on TST, since this was quite a while ago. Opening in a new tab (background or not) from the SSS popup seems to place the tab as a child of the currently open tab, which is the expected behavior. Can you please confirm if it works on your end as well, if you still use SSS and TST?

Sorry for taking this long!

Daniel

**Comment by orodeshah** [comment] 2017-11-01 01:04
I am happy you pay attention to such details actual TST is one of the most common firefox addons
Actually SSS matches with TST ONLY to some extent, but how? 
details:

1) first condition: we search a word in a tab by SSS that already has a child tab, SSS opens new tab as child,
     logic: SSS puts new tab beside tab next to main tab, so because next tab was a child, new tab by SSS will be child

2) second condition: we search a word in a tab without a child tab (next tab to main tab is NOT its child), now SSS new result page is NOT a child , so here it does not match logic of TST !!!!!!

**Comment by orodeshah** [comment] 2017-11-01 01:05
I am happy you pay attention to such details actual TST is one of the most common firefox addonsActually SSS matches with TST ONLY to some extent, but how? details:
1) first condition: we search a word in a tab by SSS that already has a child tab, SSS opens new tab as child,     logic: SSS puts new tab beside tab next to main tab, so because next tab was a child, new tab by SSS will be child
2) second condition: we search a word in a tab without a child tab (next tab to main tab is NOT its child), now SSS new result page is NOT a child , so here it does not match logic of TST !!!!!!

so second condition needs more work ti fully match with TST
    On Tuesday, October 31, 2017, 6:42:25 PM EDT, Daniel Lobo <notifications@github.com> wrote:  
 
 
It's been a long time, but SSS is finally a WebExtension, so I was looking into this, as I mentioned in issue #21 just now. I installed Tree Style Tab from here: https://addons.mozilla.org/firefox/addon/tree-style-tab/

However, I couldn't find anything wrong with running it alongside SSS. Maybe something was changed on TST, since this was quite a while ago. Opening in a new tab (background or not) from the SSS popup seems to place the tab as a child of the currently open tab, which is the expected behavior. Can you please confirm if it works on your end as well, if you still use SSS and TST?

Sorry for taking this long!

Daniel

**Comment by CanisLupus** [comment] 2017-11-01 22:27
Hi orodeshah, you're completely right. I somehow tested the only way that actually works. Clearly not a good testing job! :(

I'll keep this open until I can do something about it.

**Comment by CanisLupus** [comment] 2018-02-11 11:51
Hello orodeshah!

So, I was looking at this today and found out that SSS's behaviour seems consistent with Tree Style Tab now. I've tried it on tabs with and without children, and in every case it seems to add new tabs as children.

This is not magic. ;) In a very recent update I made SSS inform new tabs of which tab created it, which I suppose is what Tree Style Tab uses to organize its tree-tabs. That seems to have fixed this incompatibility.

Can you confirm if it works for you in the most recent SSS version? I would greatly appreciate it! :)

A thing worthy of note is that this only works on Firefox 57 or later, because the "openerTabId" attribute only exists after that version.

Cheers!
Daniel

**Comment by CanisLupus** [comment] 2018-04-18 18:54
Hey, I'm closing this, but if you find that the problem reappears feel free to comment here! :)

**Closed by CanisLupus** 2018-04-18 18:54 UTC
Labels: incompatibility
