### ISSUE TITLE
SSS popup not working on certain webpages

### ISSUE THREAD

**Issue by theorist-complex** [CanisLupus/swift-selection-search#47] opened 2017-11-03 11:41 UTC
Sorry it took me longer than I thought to get this up - IRL things took precedent yesterday. My bad.

Anywho, this started happening pre 3.4.0 though Im not sure exactly which version specifically.

I've forgotten all but a couple pages this has happened on and I went through my history and tried to find some others, but alas the following examples are the only two I can come up with right now:

- https://horaro.org/ - though it also happens on all of the scheduling pages, such as 
https://horaro.org/questingforglory/schedule

- https://addons.mozilla.org/en-US/firefox/addon/adblock-for-firefox/ - though as far as I can tell this happens on the base https://addons.mozilla.org page and all of the specific addon pages, such as https://addons.mozilla.org/en-US/firefox/addon/swift-selection-search/ - this goes for both the old and new website designs they seem to be implementing recently.

The one thing I have noticed is that both of these pages, and from what I remember of the other pages this has happened on, none of them adhere to my global custom text selection CSS style. No idea if that means anything or not, but just though I would mention it.

If you need any more info, don't hesitate to ask. 

[edit] I found another site...

- http://www.mushrecords.com/release/52 - The Mush Records homepage (http://www.mushrecords.com) seems to work, but all artist (ex: http://www.mushrecords.com/artist/Brothertiger.php), release, and other pages seem to NOT work. Also should mention that this website does adhere to my global text selection CSS style - so maybe that has nothing to do with things after all.

**Comment by CanisLupus** [comment] 2017-11-04 15:09
Hi theorist-complex, no problem at all! I was away for most of yesterday so I could only look at this now. Thank you very much for the example URLs. :) It makes it easy for me to reproduce the problem, and indeed I can confirm that SSS doesn't work in any of them.

I suspect this has happened since _at least_ SSS 3.0.0, though it could have happened before too. It depends on whether or not the websites were like this before.

addons.mozilla.com I knew. :) It has a very strict content policy, which I'm not sure if it's only defined in the website pages or enforced by Firefox itself for this specific domain. It blocks all page scripts from working there ([here](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_scripts) they even say "Note that content scripts are currently blocked on addons.mozilla.org. If you try to inject a content script into a page in this domain, it will fail and the page will log a CSP error."). This may be done to avoid extensions doing things like hiding competitor addons, auto-pressing install buttons, etc. :)

Another website I know has content policies is bugzilla.mozilla.org (see issue #27), which seems to block most icons from appearing on the SSS popup. I believe the other sites you linked have similar policies. From horaro.org I got a content error in the Firefox web console that says:

`Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src https://horaro.org [...]”). Source: #swift-selection-search-popup, #swift-se....`

so it is blocking the formatting of the popup (it is there in the page, but completely hidden). It may be the reason why your custom styles are not being applied either.

Finally, the last example with the artists page may be an SSS bug! I investigated and the popup position is being set at -106px (note the "minus"), which is above the page that you can see. There's likely something different in the configuration of the artists pages that I haven't taken into account. It doesn't seem to be blocking anything, hence why it works on the main page and for your styles. Will look into this.

As for the content policies, I don't know if it can be fixed somehow (apart from the user disabling the check in Firefox, which I don't recommend), but I'll also try and see. Either way, the context menu at least seems to work, it's just content that gets added to the page that doesn't, such as SSS's popup.

Cheers!
Daniel

**Comment by CanisLupus** [comment] 2017-11-04 15:38
Alright, the problem with http://www.mushrecords.com/release/52 is that everything in the page is absolute-positioned, so nothing occupies real space and the actual HTML height is 0. So SSS detects that the popup is bigger than the page and tries to reposition it in a wildly unsuccessful way. ;)

I've fixed it by disallowing the popup to be moved to negative positions. If it tries that, the popup will instead stay where it is. I haven't the fix to the market yet (will try changing some other things first), but the next version will have the fix. Thanks!

The content policies are still a problem, so this will stay open. :)

**Comment by CanisLupus** [comment] 2017-11-07 22:49
I just submitted version 3.6.0 to the market. I was able to fix the problem with https://horaro.org and most other sites that block custom styles. Since scripts are not blocked, I moved all CSS formatting to pure Javascript, adding the formatting to each element. This was not fun! ;) The popup animation was being a pain and I even found a Firefox bug in the process. They told me of a workaround that worked, so all is fine, hopefully.

I'll close this since all reported sites are working now (except AMO, but I can't do anything there, unfortunately). However, you may find more in the future. If you do, feel free to reopen this issue or create a new one if you'd prefer.

Thank you very much! :)

**Closed by CanisLupus** 2017-11-07 22:49 UTC

**Comment by theorist-complex** [comment] 2017-11-08 12:34
Somehow missed your posts 4 days ago...but thanks for all the info. It answered a couple of questions I had floating around in my head.

3.6.0 seems to be working very well now. Thanks again and great work!
