### ISSUE TITLE
Different spacing in v2.13.3

### ISSUE THREAD

**Issue by Gitoffthelawn** [CanisLupus/swift-selection-search#13] opened 2016-12-12 06:28 UTC
The gap between the first row and the second row is greater in v2.13.3 as compared to the prior release (too much of a gap for my preference).

If you need more info, just ask. :)  I'm juggling many tasks, so I apologize that I am keeping this brief.

**Comment by CanisLupus** [comment] 2016-12-12 19:12
It's no problem. The default is everyone being busy. :)

Hmm really? That's weird. I've just compared both SSS versions on my Firefox and both draw the same panel on a 2x2 grid (same size, same positions). I've also added the new copy and link icons to see if they would make a difference but it still looks the same.

When you can (no need to rush) could you tell me:
1. Is there any chance that the SSS preferences for icon size or icon padding have changed?
2. Does it happen to you with both copy and link icons off? Does it make a difference?
3. Do any of the icons look bigger than the others?

I haven't changed the icon sizes but sometimes the problem is where we don't expect!

**Comment by Gitoffthelawn** [comment] 2016-12-12 20:27
First, thanks for your understanding. :)

What I was seeing must have been some sort of bug, likely a timing issue.  Very possibly nothing to do with your extension.

I normally see three rows in SSS.  But it was only showing two rows, with odd spacing between the rows.

Now, as I prepared to answer your questions, it is showing three rows, looking perfect.

Since I can't reproduce the bug at the moment:

   1. If the new data above makes you think this is an SSS issue, best to leave this issue open.
   1. If you think it's not an SSS issue, best to close this issue; we can reopen if it happens again.

Hope that helps!

**Comment by CanisLupus** [comment] 2016-12-12 20:45
Alright! As we're not sure yet, I'll leave it open and mark it as "needs more info". If nothing new comes up I'll delete it after a while.

If it happens to you again or only on a specific site, that may worry me a bit. ;)

Cheers!

**Comment by Gitoffthelawn** [comment] 2016-12-13 07:00
Sounds great!  Thanks!

**Comment by CanisLupus** [comment] 2017-10-28 15:03
Closing this now. It has been a while. :) Please reply or create a new issue if this ever happens again (especially since now it's a WebExtension with likely other kinds of bugs).

**Closed by CanisLupus** 2017-10-28 15:03 UTC
Labels: needs more info

**Comment by Gitoffthelawn** [comment] 2017-10-29 07:15
I'll let you know if I see it happen again.
