### ISSUE TITLE
Rotate icons on hover

### ISSUE THREAD

**Issue by ZIEXED** [CanisLupus/swift-selection-search#62] opened 2017-12-21 00:07 UTC
Icon hover behavior > scale & rotate

_I hope the mail reached your inbox :D_

**Comment by CanisLupus** [comment] 2017-12-23 12:35
Hi! Yup, I got the mail. :) The CSS portion is the animation you wish to use, right?

I was thinking that the easiest way to implement most of these more specific visual customizations would be to support custom CSS (like a text area in the SSS options page where you could write CSS code to format the popup and icons). However, then I think I'd face a problem that I had before, where some sites would block CSS completely (to solve that I had to ditch CSS and manually place formatting on the popup elements using JavaScript). Hmm...

**Comment by ZIEXED** [comment] 2017-12-23 16:10
Yep :)
I think we are on the right path?
Providing options in the settings page would allow most users to customize them to there needs without any CCS knowledge

**Comment by CanisLupus** [comment] 2019-12-02 18:04
Hi ZIEXED. :)

OK, this might not be what you were looking for, but after consideration (I had 2 years for that, apparently!) I've decided to add a custom CSS option in version 3.40.2. I actually added an extra option for scaling icons on hover too, but decided that the rotation was a bit too specific to your request. I hope you understand. :)

The reasoning is also that if it's me (or any other coder) adding all possible animations, it would soon become hard to maintain this part of SSS and to check that things don't break on each version. So I decided to let those kinds of things be formatted by users if they know CSS and really want to do so. Custom CSS will be marked as "experimental" until I can confirm that it works as expected, however.

For your specific case (I have your email ;)), I believe you can do this:

- Set "Icon hover behaviour" (in "Popup/icons look") to "Nothing".
- Enable "Use custom CSS formatting (experimental)" (also in "Popup/icons look").
- Add this to the text field (I left out the shadow):

.sss-content img {
	transition: all 0.2s ease-in;
}
.sss-content img:hover {
	transform: rotate(360deg) scale(1.5);
}

- The bad part is that I'll inevitably have to change the internal popup formatting for some future unknown update, and so a future update may automatically turn off the Custom CSS checkbox, to avoid immediate problems (it should keep your CSS formatting text intact, however, so you could re-enable the option after you check that everything is fine [or not] in that hypothetical update).

**Closed by CanisLupus** 2019-12-02 18:04 UTC
Labels: enhancement
