### ISSUE TITLE
Performance impact

### ISSUE THREAD

**Issue by Gitoffthelawn** [CanisLupus/swift-selection-search#29] opened 2017-05-21 20:47 UTC
Hi Daniel,

I hope you are doing well. :)

I noticed that `about:performance` is reporting some "slow downs" from SSS, as well as an occasional "alert".  Maybe you'll have a chance to look at it?

It might be resolved if/when you make the move to WebExtensions.

My regards to you!

**Comment by CanisLupus** [comment] 2017-05-22 18:11
Hi there!

I'm fine, thank you. I hope you are, too. :)

Truth be told, I didn't know about the performance page, but mine is reporting light green and close to no impact on performance for SSS. I only got it to dark green and 6/10 framerate impact by constantly double clicking a word in a page, causing the popup to appear repeatedly. ;) On my Firefox only LastPass and uBlock are apparently having alerts (a lot of them for LastPass, actually).

Do you know of something that could be causing SSS to behave badly on your machine? Number of open tabs? How long ago did you start Firefox? Do you have the "Popup location" setting set to "At cursor location"? (it's a little more demanding, as it registers with the mouse move event, although I have that option on for myself and see little difference, but it depends on the machine, of course).

Cheers for caring about performance! The web is a magical place of things that take too long to happen. :)

Regards,
Daniel

**Comment by Gitoffthelawn** [comment] 2017-05-22 19:47
I'm doing okay.  Dealing with a health issue, but I'm a fighter.  Thanks for asking.

Glad I pointed out the performance page to you!  I do have a greater performance impact than you are experiencing (according to  about:performance).

> Do you know of something that could be causing SSS to behave badly on your machine?

Extension conflicts could be a possibility.  Turning down the CPU frequency when not doing anything too CPU intensive.  Possibly different pointing device drivers, but I don't think Firefox would be able to measure that.

> Number of open tabs?

Nope.  I generally have less than 10 open.  After that, my brain explodes. ;)

> How long ago did you start Firefox?

I start it more than once per day, on average.

> Do you have the "Popup location" setting set to "At cursor location"? (it's a little more demanding, as it registers with the mouse move event, although I have that option on for myself and see little difference, but it depends on the machine, of course).

Yes, I do.  I haven't tried changing that yet.  Simple enough to try.

> Cheers for caring about performance! The web is a magical place of things that take too long to happen. :)

I recently was told "who cares about performance, it's a non-issue!".  My eyes rolled to the point I wasn't sure they would return.  8-)  Glad you care too!  :-)

**Comment by Gitoffthelawn** [comment] 2017-05-22 20:01
Oh, I almost forgot... for `about:performance` to be most useful for this sort of testing, be sure to ***uncheck*** "Display only the last 10s".

**Comment by CanisLupus** [comment] 2017-05-23 21:55
> I'm doing okay.  Dealing with a health issue, but I'm a fighter.  Thanks for asking.

I'm sorry to hear that. I hope it's not too bad... and that you fight back and get better! :)

> Nope.  I generally have less than 10 open.  After that, my brain explodes. ;)

I can understand that, though I can open upwards of 30 when I'm researching something, even if many are obsolete right after opening them. :)

Thank you for answering all the questions. Everything seems pretty standard on your end. If you're able to pinpoint the causes of the alerts please tell me. I will see if the WebExtensions port makes a difference (I've only worked on it twice, but should continue soon enough) and try to optimize any obvious slowness using the performance page. And yes, I also tried without "Display only the last 10s". :)

> I recently was told "who cares about performance, it's a non-issue!".  My eyes rolled to the point I wasn't sure they would return.  8-)  Glad you care too!  :-)

Ouch! Computers and networks are getting faster constantly, but some applications I use daily are nevertheless getting _slower_ with each update. I think this qualifies as an "issue". ;) It really depends on the context and what is slow. Maybe taking 100ms when the user presses a "sort" button in a UI is not a big deal, but try that in a video game and you'll have a bad time (even if 100ms _should_ be considered a very long time for most offline applications). And a website that takes 5 seconds to open on sub-stellar Internet connections wastes tens of thousands of seconds for humanity per day. ;)

**Comment by Gitoffthelawn** [comment] 2017-05-24 01:01
> I'm sorry to hear that. I hope it's not too bad... and that you fight back and get better! :)

Thank you so much.  I hope so too!  You keep being awesome, and I'll keep fighting! :)

> Thank you for answering all the questions. Everything seems pretty standard on your end.

No problem at all.

> If you're able to pinpoint the causes of the alerts please tell me.

Do you know what Firefox means by "alert" in this context?

> I will see if the WebExtensions port makes a difference (I've only worked on it twice, but should continue soon enough) and try to optimize any obvious slowness using the performance page.

Looking forward to it whenever you have the time.

> Ouch! Computers and networks are getting faster constantly, but some applications I use daily are nevertheless getting slower with each update. I think this qualifies as an "issue". ;) It really depends on the context and what is slow. Maybe taking 100ms when the user presses a "sort" button in a UI is not a big deal, but try that in a video game and you'll have a bad time (even if 100ms should be considered a very long time for most offline applications). And a website that takes 5 seconds to open on sub-stellar Internet connections wastes tens of thousands of seconds for humanity every day. ;)

I agree completely.  I've found some things with technology are getting slower and slower even though the hardware specs keep getting faster and faster.  Very little should leave the user waiting nowadays, but often we all now have to sit and wait for the busy cursor to spin and spin or for the progress bar to inch its way across the landscape... ;)

**Comment by CanisLupus** [comment] 2017-05-24 17:49
>  You keep being awesome, and I'll keep fighting! :)

Haha, it's a deal. ;)

> Do you know what Firefox means by "alert" in this context?

Not really. It seems to connect the alerts to framerate, but otherwise I have no idea what criteria Firefox has for counting them. I'll try leaving the page open all the time while I use the browser normally and see what I get.

> Very little should leave the user waiting nowadays, but often we all now have to sit and wait for the busy cursor to spin and spin or for the progress bar to inch its way across the landscape... ;)

Exactly! :) A few weeks ago I was watching a talk by Jonathan Blow about his new programming language and he showed an example of Photoshop taking about a full second to open a "New" file window on a good laptop. Not just the first time, but every time. Somehow we almost consider this "normal", but it's actually _very_ slow. 😱

**Comment by Gitoffthelawn** [comment] 2017-06-22 22:21
Just a short followup.

about:performance still showing issues with Swift Selection Search.

Just typing this note on GitHub has caused 6/10 impact on framerate with 1 alert.  Besides this tab and the about:performance tab, only 1 other tab open right now.

Sometimes the browser feels faster doing things like typing in forms like this one than other times, even when starting a new session.  Looking at the browser console, it suggests that *possibly* there is a delay during the ***reflow*** process.  I'm not sure of the culprit, but I thought I would mention it.

Let me know if you get a chance to look at the performance issues.  No pressure.... I know you're busy too. :)

**Comment by CanisLupus** [comment] 2017-10-28 15:08
Hey, I missed replying to you on this. Sorry!

If you have any performance issue now that SSS is a WebExtension please reply. I don't think I changed anything relevant to performance, though, apart from when the popup appears. On idle there should't be any difference.

If there are no apparent problems I'll close the issue eventually, as usual. :)

**Comment by Gitoffthelawn** [comment] 2017-10-29 07:14
No problem!

Happy to see the new WE version go live!  Congrats!

Is there any performance impact when the popup is not actively being shown?

**Comment by CanisLupus** [comment] 2017-10-29 09:57
Yay, thank you! :)

It seems Mozilla actually removed the add-ons from the about:performance page for now (I hadn't noticed). As I understand it (https://bugzilla.mozilla.org/show_bug.cgi?id=1309946), it seemed to be triggering warnings for little reason and wasn't being useful. I expect that's what was happening with SSS, though in my machine it seemed fine anyway. :)

The only performance penalty I can think of in idle mode is registering with the mouse move event to then allow the popup to appear at your cursor position when needed (if you have that option selected). This already happened before the WE version. The mouse down event is not enough to get position, because you might select text with the keyboard before even moving the mouse. I tried a few approaches but couldn't find a better way yet.

The other popup location option has no theoretical impact, I believe.

**Comment by CanisLupus** [comment] 2017-10-31 23:04
I'll close this but feel free to reply (or create a new issue) if you ever feel SSS is slowing Firefox down. In any case, I have written down a note to remind me to check if I can improve the usage of mouse events when I have time for that. :)

**Closed by CanisLupus** 2017-10-31 23:04 UTC

**Comment by Gitoffthelawn** [comment] 2017-11-01 00:18
Great!  Thanks!
