### ISSUE TITLE
Suggestion: editable search engines!

### ISSUE THREAD

**Issue by Teko101** [CanisLupus/swift-selection-search#37] opened 2017-10-28 23:48 UTC
Hi Daniel,

Thanks a lot for the new SSS WE version, I'm really glad you released it before FF hits version 57.

Currently I'm having a problem using "multiple rows" , 
Please take a look at the bottom row:   https://i.imgur.com/AJ0Ntir.png

Is it possible to add an option for changing the "Icon vertical padding" ? ( just like the "Icon horizontal padding" option)

Also could you please make the "imported search engines" editable?

Cheers.

**Comment by jdreesen** [comment] 2017-10-28 23:53
> Also could you please make the "imported search engines" editable?

Yes please! That would be awesome.

**Comment by CanisLupus** [comment] 2017-10-29 09:43
Hello! Now that you mention this, it makes sense. I made them uneditable without thinking too much because internally they are a different category of engines and have a few differences. Their icons are usually raw data and not URLs, and also because they can be reimported from the engines file without getting duplicates of already imported engines.

However, these are not strong points at all! :) I'll try to change that later. Maybe make it so that as soon as you edit them they become "normal" custom engines (this is an internal detail and nothing the user should worry about).

As for the grid view and padding, I'll also look into that. I don't have that many engines but it should be easy to reproduce. ;)

**Comment by CanisLupus** [comment] 2017-10-29 16:30
It seemed that some webpages were causing the space between rows to be greater than it should, pushing some icons out of the popup, which was... curious, since I reset all page formatting before applying my own formatting. Then I found out that the reset did not include font-size, so any page that changed font size affected the popup (since everything is text-based even if it's all images).

It's fixed now and I've submitted a new version to AMO, 3.1.0.
I've also added a setting for vertical icon padding. :)
And I've added the possibility of deleting imported engines. This was an oversight on my part. It should have always been possible!

As for the actual title for this issue, "editable search engines", I'll look into that after I solve some other things. :)

**Comment by Teko101** [comment] 2017-10-29 18:56
WoW!!
I didn't expect to get SSS fixed that fast! 

Honestly I'm glad that this "grid view" problem happened! otherwise I wouldn't have mentioned the "vertical padding" option which I really wanted from the very first version, so thank you :)

As you mentioned "font-size" issue , I think the "popup menu" also get affected by "page direction" (RTL to be specific)
This is not a big problem for me as I rarely use RTL webpages, but I noticed that the horizontal order of the "popup buttons" changes whenever I access an RTL page.

Anyways, I really appreciate your work.
Best Regards.

**Comment by CanisLupus** [comment] 2017-10-30 21:40
Hehe in truth I'm not usually this fast with SSS updates. ;)

You're welcome! Thank you for reporting the problem. I hadn't added vertical padding before because some of the highlight modes (when you hover icons with the mouse) depended on a fixed padding, so it involved moving a few things from CSS to JavaScript to solve that. But it was relatively quick after all.

Very interesting point about RTL! I never thought about it but it makes sense, of course. I've reproduced it easily and I'll keep it in mind for fixing in a later update. :)

Cheers!

**Comment by CanisLupus** [comment] 2017-11-11 14:46
Version 3.7.0 now lets you edit the imported search engines! ;) As usual, if you find any problem with it, please reply or create a new issue.

@Teko101 I completely forgot to tell you, but I believe I fixed the icon order on RTL pages from version 3.5.0 on. :)

**Closed by CanisLupus** 2017-11-11 14:46 UTC
Labels: enhancement
