### ISSUE TITLE
Panel positioning out of the screen

### ISSUE THREAD

**Issue by pintassilgo** [CanisLupus/swift-selection-search#22] opened 2017-01-16 16:49 UTC
If you select at the lower edge of the screen, the panel should be positioned so that you don't need to scroll the page to see it.

Current:
![](http://i.imgur.com/TQZW69b.png)

Should be:
![](http://i.imgur.com/QaLLnRI.png)

**Comment by CanisLupus** [comment] 2017-01-17 19:16
Thank you for opening this issue. In fact the panel is supposed to do exactly that - stay inside the screen, or at least inside the page, especially if the popup location is set to the cursor position.

But you are right, it's not always doing that, and I seem to have forgotten to make it work for the grid layout too! I use single row myself. :)

I'll try to fix this as soon as I get some time to work on SSS.

**Comment by CanisLupus** [comment] 2017-10-31 23:01
I believe this is fixed in the more recent versions (since 3.0.0) as I could not reproduce it now. I changed the positioning and sizes a bit while working on the WebExtensions version, so that probably fixed it. You told me you won't be moving to WebExt now so I'll close this issue, but if this ever happens again in the new versions please reply. :)

Cheers!

**Closed by CanisLupus** 2017-10-31 23:01 UTC
Labels: bug
