### ISSUE TITLE
searching via Google appears to disable some of the scripting on Google's site??

### ISSUE THREAD

**Issue by maboroshix** [CanisLupus/swift-selection-search#155] opened 2019-11-25 09:10 UTC
**Describe the problem**
Hello guys, when I highlight some text and click on Google in the popup selection box, it will properly bring up the search in a new tab -- however, it appears to disable some of the scripting on the new Google search tab? For example, I am unable to scroll through the videos listed after the very first link shown i.e. cannot click on the arrow to scroll horizontally through the videos listed. I'm also unable to click on the links to the videos themselves. If I bring up Google from a bookmark and then do the exact same search by manually typing in the exact same text, however, I can scroll through the videos listed 
and click on through via the links. 

What exactly is going on? I do have UMatrix but I can't imagine this behaviour would only show up in one case and not the other. 

**How to reproduce the problem**
1. highlight text to bring up pop up box
2. Click on Google icon to search for highlighted text
3. on newly summoned Google search tab, try to click on arrows to scroll through videos below first link listed; for me, I'm unable to do so. Also unable to click on direct links to videos themselves.

**Anything else you'd like to include**
What you tried already, screenshots, attachments, examples, etc.

**System info:**
- Browser: Firefox
- Browser version: 70.0.1
- System: Windows 7, up to date on critical / important patches

**Comment by CanisLupus** [comment] 2019-11-25 18:54
Hello!

Unfortunately I haven't been able to reproduce this on my end (tried on 70.0.1 and 63, with several extensions and none, respectively).

We're talking about this section, right?
![image](https://user-images.githubusercontent.com/532708/69568892-6cac9100-0fb4-11ea-9d88-aa436e0eb565.png)

It's likely that another addon conflicting with the page. Do you only have UMatrix installed besides SSS? Try disabling all addons but SSS and see if the problem disappears. Please let me know. ;)

- Daniel

**Comment by CanisLupus** [comment] 2019-12-02 19:49
I'm closing this due to the need for more information to confirm the problem, but feel free to reopen it if you find that SSS is really causing this.

Cheers!

**Closed by CanisLupus** 2019-12-02 19:49 UTC
