### ISSUE TITLE
Popup appears when editing text on some sites

### ISSUE THREAD

**Issue by Gitoffthelawn** [CanisLupus/swift-selection-search#1] opened 2016-06-22 21:01 UTC
First, thank you for your most excellent extension! :-) :+1: 

Second, welcome to GitHub! :-) :+1: 

Third, I find your extension works great.  But in some ways, it works too well!  When editing text in certain sites, the search popup appears even though it is not desirable.  For example, when editing an email in gmail, the search popup appears when the user is entering their email text and they use shift+left arrow to highlight text in order to replace it.  On other sites, such as GitHub, this does not happen, and it works perfectly.

Maybe you can take a look at it?

Tested with Swift Selection Search on Firefox 47.0.

**Comment by CanisLupus** [comment] 2016-06-23 19:32
Thanks for the report and kind words. :)

The Add-on SDK is unfortunately free to choose when to trigger text selection on a page. This annoys me too because I use Gmail frequently as well. I believe it depends on the type of HTML element where text is selected. On explicit text boxes the SDK does not trigger the event (this is correct) but I believe Gmail does not use them.

A possible solution to this would be adding a blacklist of sites where text selection should not trigger, but this would disable the add-on fully on Gmail, and I don't think that is the best option. Maybe it should detect the compose area specifically... :)

**Comment by Gitoffthelawn** [comment] 2016-06-24 05:15
You're welcome.  Thanks for the great extension.

Take a look at this similar (yet currently inferior) extension: https://github.com/edawn/selected-search-firefox-addon

IIRC, it handles gmail correctly.

If looking at that code doesn't provide an answer, it's possible to add blocking by Xpath or by CSS3 selectors.

**Comment by CanisLupus** [comment] 2016-07-21 23:02
My apologies for only replying now! I intended to change the addon to not use Firefox's panel and instead rely on pure HTML and Javascript, so I've been making a lot of changes and fixes to SSS on my spare time. I was not sure if it would help or not. It's been a while. :)

It has helped and, in addition, many requested features have been added, but now I have a couple of issues I'll have to solve before submitting the changes to Github (and Mozilla's addon page), so it might be another while.

About your request... I haven't implemented it directly, not because I can't, but mostly because I don't like the idea of checking specific classes/IDs on a page for every selection made (to see if we are on Gmail's compose window), and because there are probably a lot more places in the Internet where a special check would have to exist (Outlook is another one I know of).

However, I'm planning on adding a keyboard shortcut to disable the popup (until the shortcut is pressed again), so that those irritating places can be dealt with in a less-than-ideal-but-works-for-everything way.

I realize this is probably not how you wanted the fix (me neither, for that matter!). I'll leave the issue open and look into this later (for the more important Internet places) if people feel this isn't nearly enough. Anyway, enough text. :) What do you think?

**Comment by Gitoffthelawn** [comment] 2016-07-22 06:57
I think I'm excited you are working on it! :-)

I don't want to look a gift horse in the mouth, but here's my thoughts on the workaround idea.  Overall, honestly, I don't like it.  I agree that checking for specific classes/IDs for every selection is hardly ideal.  Perhaps some other similar extensions have implemented a better method.

That said, even if a list of specific classes/IDs needs to matched, it can be kept small enough that it shouldn't noticeably impact performance.  Ideally, the list will be editable by the user so they can add any classes/IDs for their favorite sites.

***Here's another idea:*** What if instead of disabling it for certain classes/IDs, you instead disable it for certain elements?  TEXTAREA, FORM, INPUT immediately come to mind.  Actually, the SDK might take care of some of those.  If you also disable it for any element with the [`contenteditable` attribute](http://www.w3schools.com/tags/att_global_contenteditable.asp) set to `true`, you might cover just about every case without having to check for specific classes/IDs.

**Comment by Gitoffthelawn** [comment] 2016-07-22 23:11
Also, definitely want to disable it on URI's using the `chrome` and `resource` protocols.  I think Firefox disables it on `about` pages, but you might want to confirm that the extension is not causing issues on those pages.

**Comment by CanisLupus** [comment] 2016-07-22 23:39
Thanks for being honest! :) The contenteditable suggestion might help, at least in Gmail's case. I'll see about it. I'll go for the solution that is easier to scale. I'm not terribly worried about performance unless there are dozens of different checks for different websites, but I do worry about solving the problem in a maintainable way.

As for forms, text areas and similar, I also believe Firefox handles that, hence why it doesn't show in Google's search bar, for example. I've briefly checked a few chrome pages and everything seems normal on my end.

Thanks for the enthusiasm and help! ;) It's much appreciated.

**Comment by Gitoffthelawn** [comment] 2016-07-23 11:23
You're welcome!  And thank YOU for creating such a useful tool.

I also have ideas for some interesting enhancements, whenever you would like to hear them.

**Comment by CanisLupus** [comment] 2016-07-24 22:40
You're also quite welcome. :)

Sure, let me know about them! I've been implementing some requested features in the reviews and emails I got, so some of them might already be covered (or not!). Still have to sort out a few things, though. :p

Release changes:

Features
- Any key press should now disable the popup (except ctrl, shift, alt, cmd, etc).
- Added option to set the duration of the panel opening animation (0 disables it).
- Added optional auto-copy of selected text.
- Added option to make popup appear at mouse position.
- Hovering popup icons now shows a tooltip with the name of search engine.
- Added keyboard shortcut to disable panel (until pressed again).

Fixes
- Popup should not appear anymore on HTML elements with contentEditable set to true. This solves cases like Gmail or Outlook's compose window.
- Ctrl+click should now always open in a new (background) tab.
- Browser sidebars and zoom will now correctly affect the popup position.
- Popup panel now scrolls with the page if disable on scroll is not active.
- Popup won't leave the page or display over browser elements anymore.

**Comment by CanisLupus** [comment] 2016-07-24 22:41
Maybe you already know but I found that there's an isContentEditable property that immediately tells if the element is editable without having to search up the document and skip all contentEditables set to "inherit" until a "true" or "false" is found. :) However, it can be undefined for some elements, so some traversing is still necessary.

The implementation became:

`	// disable popup in contentEditable elements, such as Gmail's compose window
	for (var elem = s.anchorNode; elem !== document; elem = elem.parentNode)
	{
		if (elem.isContentEditable === undefined) {
			continue;	// check parent for value
		} else if (elem.isContentEditable === true) {
			return; // quit
		} else /*if (elem.isContentEditable === false)*/ {
			break; // create popup
		}
	}`
...and it solves the issue for Gmail and Outlook, like I said in the release notes, and probably many other places, so that's great and it's thanks to you! ;)

**Comment by Gitoffthelawn** [comment] 2016-07-24 23:15
That looks great! :-)  Well done!  :+1: 

I'll post some enhancement ideas that might be appropriate for the next version.  To keep things readable, I'll create a new issue for each one.

**Comment by CanisLupus** [comment] 2016-07-30 18:02
Hi again! :)

Thanks for your suggestions. I've read and logged them. Can't promise to do anything about them yet, but I certainly think they would be useful. If you have more ideas, please share!

I've pushed all my changes to the repo. I'm not submitting to Mozilla's add-ons just yet because there are big changes internally and there might exist some issue I'm not seeing.

I'd like to ask you if you could use the new SSS version for a while (2.0.0, in the "build" folder) and tell me if you find anything wrong with it. I'll be doing the same, as I use Firefox everyday. If there's anything wrong there's the old version (1.3.0) in the same folder for reverting.

If you don't want to do it that's perfectly fine, really. :) It would just help to find any glaring issue before everyone gets the new version officially. After a while I'll upload to Mozilla and finally start responding to all the reviews and mentioning the changes people suggested! Phew!

**Comment by CanisLupus** [comment] 2016-07-30 18:03
I'll also close this issue and the popup panel position one as soon as version 2 is considered "gold". That is, if the "content editable" solution is found to work nicely in the relevant places.

**Comment by Gitoffthelawn** [comment] 2016-07-30 18:19
Yes!  I will definitely test it for you.

Things are going to be a little challenging in 3 days when Mozilla enforces the inability to test unsigned extensions in the release build.  Will have to look at the unbranded versions of the browser for testing purposes.  As an alternative, I think you can publish a developer version on AMO that will be signed, but only available for users who want to try it.  Would you mind taking a look at that possibility?

**Comment by CanisLupus** [comment] 2016-07-30 18:48
Hmm... good thing that you remind me of that. I've checked now and it seems that I have the ability to make my addon unlisted or hidden, but not its versions. A beta channel could work, but quoting Mozilla: "Beta channels are only available to fully-reviewed add-ons.", and SSS is not a fully reviewed add-on. Not because I haven't tried. :( At some point it was in the review queue for more than a month and other add-ons were getting constantly prioritized, so I was even falling down positions after that time... I thought that was insane. :|

**Comment by Gitoffthelawn** [comment] 2016-08-01 04:20
Yes, many people have expressed frustration over that review queue.  It is insane, especially given that Mozilla's future largely depends on good extensions.

I also read that quote about the beta channels only being available for fully reviewed extensions.  I think Mozilla's inconsistency of verbiage confused me, however.  On AMO, there are "Developer Channels".  They don't show them as "Beta Channels" (despite them using that term in the documentation), but I think they are likely the same thing.  If that's the case, then it probably won't be an option at this time.

One possibility is to release the latest version on a day that you have some time, and update the extension's description to tell people that there were some large changes and to come here and post any issues.  If there are major issues, people can always use the "Version" section on AMO to get the previous version.

BTW, since the extension is not fully reviewed, it won't show up when people search for it on `about:addons`.  At some point, you may find it best to put it in the full review queue again.  Mozilla recently hired a new employee to perform reviews, so hopefully the queues will be a little better going forward.

**Comment by CanisLupus** [comment] 2016-08-01 21:05
I will definitely try the full review at some point. I was just discouraged last time. :) The extra employee is good news.

I also found out yesterday that SSS isn't working in multiprocess Firefox. I created an issue for that. I just hope it's something wrong on my SDK setup and not an SDK bug.

**Comment by Gitoffthelawn** [comment] 2016-08-03 04:43
Congrats! :tada: That's great news!

So far, the new version is working fabulously!

**Comment by CanisLupus** [comment] 2016-08-03 13:25
Thanks a lot for your help and interest in SSS! It's really appreciated. :) I'll be away for a few days, so I hope any big problems will wait for me to return. ;)

I found panel formatting bugs in a few websites, so I added a fix for that yesterday, but it's still awaiting review. If you get similar issues, version 2.0.2 should be live soon (I think).

**Comment by Gitoffthelawn** [comment] 2016-08-03 19:09
You're welcome.  The big thanks go to ***you*** for creating such a useful extension.

I am now using version 2.0.2, and have not had any issues.

Have a good trip... enjoy your break from technology!

**Comment by CanisLupus** [comment] 2016-08-03 23:04
Thanks! Will do! :)

**Comment by T-Halen** [comment] 2016-08-26 15:38
Sorry to jump into this thread, but the latest Firefox update forced me to switch context search addons, and I came upon this one which works pretty well, but I was disappointed to find that I can't select and search on text in a FORM field.  Obviously this is completely opposite from the original request.

So I guess my question would be, is there a way to set a preference for allowing a search on selected text in a FORM field?

If having the popup get in the way is the biggest issue, how about only allowing it from the right-click -> Search With selections?

Thanks.

**Comment by CanisLupus** [comment] 2016-08-27 10:21
Hi T-Halen,

The thing here is that Firefox simply does not trigger the text selection event when text is selected in a form or google.com's search bar, so SSS isn't able to show the popup (or even to search using "Search with" in the context menu, which is something I hadn't thought about but just confirmed that doesn't work for forms).

What would have to be done to fix this is to try to detect the text selection ourselves, probably by detecting all mouse release events and maybe some keyboard ones too (because you can select text by holding shift in a page) and get the current selection at that point in time.

After that, I could add options to work on forms, or simply allow the context menu to work. While we're on that, I believe that I could fix the context menu in forms without removing the default selection detection...

I'll look into this when I have time, which is a bit short right now! :( Anyway, your suggestion is appreciated, so don't worry about jumping into the thread. ;) I'm waiting a while before closing it (as the original issue is solved but some problem could appear), but if I do I'll create another issue for the form stuff.

**Comment by CanisLupus** [comment] 2016-09-24 10:27
Just opened a new issue for your case, T-Halen. Will be finally closing this one now. :)

Thanks,
Daniel

**Closed by CanisLupus** 2016-09-24 10:27 UTC
Labels: enhancement

**Comment by CanisLupus** [comment] 2016-09-24 11:11
I mentioned it in the other issue, but I've just added support for the context menu search in forms and other input fields (version 2.0.7). It's now awaiting Mozilla's review, but the build folder has it already.

**Comment by Gitoffthelawn** [comment] 2016-09-24 19:02
Thanks Daniel!
