### ISSUE TITLE
Search popup appearing when clicking on some links

### ISSUE THREAD

**Issue by Gitoffthelawn** [CanisLupus/swift-selection-search#19] opened 2017-01-06 22:36 UTC
I'm experiencing a weird issue that wasn't present before: When clicking on some links, the Swift Selection Search popup briefly appears before the link is loaded.

I notice it when clicking on the comment links to the right of article titles on ghacks.net.  The comment links are little speech bubbles with a number next to them.

The weird thing is that it does not always happen.  But it has happened enough times that I'm willing to open an issue for it. :)

Generally, once it happens for a link, it doesn't happen again until the browser's cache is cleared.

**Comment by CanisLupus** [comment] 2017-01-07 11:28
I tried clicking several bubble links and didn't see it happen here. :( It always opened the article and moved to the comments section without SSS triggering.

I tried it on:

Firefox 50.1.0
Firefox Developer Edition 52.0a2 (2016-12-28) (32-bit)
Firefox Nightly 53.0a1 (2016-12-27) (64-bit)

(all on Windows)

I added some code to see if the panel was being called when the comment link was clicked (it could be too fast for me to see) but it wasn't. It should only appear when text is selected, which was supposedly not the case. :)

I also tried to "drag click" the link, as maybe in some cases it could select a letter of text as you click and you wouldn't notice, but Firefox doesn't let me do that.

Could you tell me which Firefox are you using? And is it Windows? (you might have told me before, but I can't remember)

You said it didn't always happen, so I might have been unlucky. Did the panel appear at the text location? (or at your cursor, depending on your preferences) Or in some corner of the page?

**Comment by Gitoffthelawn** [comment] 2017-01-07 21:09
Ya, I had a hunch it would be challenging to replicate. :)

Issue appears on Firefox 50.1.0 (Windows).

I thought maybe it was a "drag click" issue as well, but I could not get it to do that either.

The panel appears at the text location.  It then quickly fades out as the link is loaded.

I'm keeping a close eye on it to see if can be consistently replicated in any particular situation.  So far, nothing consistent, which tells me it is likely a timing issue or a race condition.

**Comment by Gitoffthelawn** [comment] 2017-01-07 21:31
Here are steps that often work for me to replicate:

1. Clear browser caches
2. Close Firefox.
3. Open Firefox.
4. Go to https://www.ghacks.net <--- possibly important: going to the SSL version of the site
5. Click on one of the discussion links next to an article title.
6. The Swift Selection Search popup appears,

If close the **site**, and then repeat steps 4-6, it does not happen.

**Comment by Gitoffthelawn** [comment] 2017-01-07 23:19
I performed some more testing, and I can get it to exhibit the behavior about 10% of the time (which should be helpful):

  1. Go to https://addons.mozilla.org/firefox/addon/swift-selection-search/
  2. Click on the empty space to the right of the double-right-chevrons that are next to the screenshots.
  3. Move the cursor using your pointing device (mouse/trackball/etc.).
  4. Repeats steps 2-3 until the popup appears.

I hope this helps!

I tried this about 100 times, and the popup appeared about 10 times.

**Comment by CanisLupus** [comment] 2017-01-08 00:41
Thank you! Those steps were spot-on, but there is something weird going on in the add-on page. :) I can actually reproduce it 100% of the time, by clicking a little far into that area like you said, then somewhat closer to the >> symbol, then far again, etc.

The thing is, it is actually selecting something: one of the screenshots! Even though it is invisible due to the slideshow only displaying 3 images at once, they are still there, and for some reason something causes a selection that includes the image and its title. In fact, even if you have SSS disabled you should be able to right click after left-clicking the invisible screenshot and, in the context menu, you should get an option to 'Search google for "Add-on screenshot #4"' or something like it.

Maybe something like that is happening on ghacks.net? (I could not reproduce that one.) It could be due to the pages' Javascript and probably not something I can fix, unfortunately. But until I'm sure, I'll leave this issue open.

**Comment by Gitoffthelawn** [comment] 2017-01-08 07:55
Glad you were able to reproduce it.  I dislike issues that are hard to reproduce.

In the AMO example, why is the screenshots getting selected when no drag is being performed?

**Comment by CanisLupus** [comment] 2017-01-08 11:33
That is a good question. If I had to guess I would say it's the JavaScript that tries to open the larger screenshot popup. As the thumbnail is hidden, it doesn't open and causes a selection _somehow_. But this doesn't explain much about the selection itself, and it doesn't happen on Edge, for example, so I'm not sure why it happens.

**Comment by Gitoffthelawn** [comment] 2017-01-08 18:40
Hmmm... maybe we will find additional sites that provide consistent examples.

**Comment by CanisLupus** [comment] 2017-10-31 21:48
Hey :) Did you ever find more websites where this happened?

addons.mozilla.com was the only one I could reproduce but that was due to external things and actually the whole site blocks extensions from working now. ;)

Do you know if SSS still works weirdly in https://www.ghacks.net? Thanks!

**Comment by Gitoffthelawn** [comment] 2017-11-01 00:20
So far, the WebExtensions version is working quite well.  No weird behavior except what you already know about.

Overall, it's fantastic! 👍 :)

**Comment by CanisLupus** [comment] 2017-11-01 10:52
Thank you! :D [GitHub tried to convert my smiley to a dagger 🗡. How nice ;)] I'm glad you like it. 

Alright, I'll be closing this one too, then. If anything pops up (pun unintended, actually :p) please reply.

**Closed by CanisLupus** 2017-11-01 10:52 UTC
Labels: needs more info
